kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployments
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployments
  template:
    metadata: 
      labels:
          name: deployments
    spec:
      containers:
        - name: react-nginx
          image: rajpatoliya/devops-test
          ports:
            - containerPort: 80
